# Build stage for Node.js app
FROM node:14-alpine as build-stage

WORKDIR /app

COPY server/package*.json ./server/tsconfig.json ./server/pnpm-lock.yaml  ./

COPY server/prisma ./prisma

RUN npm install -g pnpm

RUN pnpm install

COPY server/src .

RUN pnpm run build

EXPOSE 8000

CMD ["ls"]