# build stage
FROM node:lts-alpine as build-stage

WORKDIR /app

COPY admin/package*.json admin/pnpm-lock.yaml ./

RUN npm install -g pnpm

RUN pnpm install

COPY admin .

RUN pnpm run build

# production stage
FROM nginx:stable-alpine as production-stage

COPY --from=build-stage /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]