FROM node:lts-alpine

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
COPY server/package*.json ./

RUN npm install -g pnpm

RUN pnpm install

# Bundle app source
COPY server .

EXPOSE 8000

FROM nginx:latest

# Remove default nginx configuration file
RUN rm /etc/nginx/conf.d/default.conf

# Copy custom nginx configuration file from the current directory
COPY nginx.conf /etc/nginx/conf.d/


RUN apt-get update && apt-get install -y curl

# Expose port 80 for nginx
EXPOSE 80

# Start node app and nginx server
CMD ["sh", "-c", "cd /app && node index.js & exec nginx -g 'daemon off;'"]

