version: '3.8'
services:
  db:
    container_name: postgres-2
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: yasar
      POSTGRES_USER: admin
      POSTGRES_DB: product_db
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
  
  cache:
    container_name: redis-2
    image: redis:latest
    command: redis-server --requirepass password
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redisdata:/data
  
  server:
    build: 
      context: .
      dockerfile: Dockerfile-Node
    container_name: server
    restart: always
    depends_on:
      - db
      - cache
    ports:
      - 8000:80
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    
  admin:
    build: 
      context: .
      dockerfile: Dockerfile-Vue
    container_name: admin
    restart: always
    depends_on:
      - server
    ports:
      - 4000:80
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
  
  client:
    build: 
      context: .
      dockerfile: Dockerfile-React
    container_name: client
    restart: always
    depends_on:
      - server
    ports:
      - 3000:80
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
  
volumes:
  pgdata:
  redisdata:

    
