version: "3.8"
services:
  db:
    image: "postgres:13"
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=yasar
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=product_db
  session:
    image: "redis:6"
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
volumes:
  pgdata:
  redisdata:
